import 'package:ppob/core/constant/constants.dart';
import 'package:ppob/core/constant/strings.dart';
import 'package:ppob/core/model/prefix_paket_data_model.dart';

class PaketDataProviderUtil {
  static Map<String, PrefixPaketDataModel> prefixModel = {
    "0856": PrefixPaketDataModel(
        prefix: "0856",
        provider: Constants.IM3,
        productCode: Constants.ISATDATA,
        productName: Strings.INDOSAT_DATA),
    "0857": PrefixPaketDataModel(
        prefix: "0857",
        provider: Constants.IM3,
        productCode: Constants.ISATDATA,
        productName: Strings.INDOSAT_DATA),
    "0858": PrefixPaketDataModel(
        prefix: "0858",
        provider: Constants.MENTARI,
        productCode: Constants.ISATDATA,
        productName: Strings.INDOSAT_DATA),
    "0855": PrefixPaketDataModel(
        prefix: "0855",
        provider: Constants.MENTARI,
        productCode: Constants.ISATDATA,
        productName: Strings.INDOSAT_DATA),
    "0814": PrefixPaketDataModel(
        prefix: "0814",
        provider: Constants.MENTARI,
        productCode: Constants.ISATDATA,
        productName: Strings.INDOSAT_DATA),
    "0815": PrefixPaketDataModel(
        prefix: "0815",
        provider: Constants.MENTARI,
        productCode: Constants.ISATDATA,
        productName: Strings.INDOSAT_DATA),
    "0816": PrefixPaketDataModel(
        prefix: "0816",
        provider: Constants.MENTARI,
        productCode: Constants.ISATDATA,
        productName: Strings.INDOSAT_DATA),
    "0896": PrefixPaketDataModel(
        prefix: "0896",
        provider: Constants.TRI,
        productCode: Constants.TRIDATA,
        productName: Strings.TRI_DATA),
    "0897": PrefixPaketDataModel(
        prefix: "0897",
        provider: Constants.TRI,
        productCode: Constants.TRIDATA,
        productName: Strings.TRI_DATA),
    "0898": PrefixPaketDataModel(
        prefix: "0898",
        provider: Constants.TRI,
        productCode: Constants.TRIDATA,
        productName: Strings.TRI_DATA),
    "0899": PrefixPaketDataModel(
        prefix: "0899",
        provider: Constants.TRI,
        productCode: Constants.TRIDATA,
        productName: Strings.TRI_DATA),
    "0895": PrefixPaketDataModel(
        prefix: "0895",
        provider: Constants.TRI,
        productCode: Constants.TRIDATA,
        productName: Strings.TRI_DATA),
    "0811": PrefixPaketDataModel(
        prefix: "0811",
        provider: Constants.SIMPATI,
        productCode: Constants.TSELDATA,
        productName: Strings.TELKOMSEL_DATA),
    "0812": PrefixPaketDataModel(
        prefix: "0812",
        provider: Constants.SIMPATI,
        productCode: Constants.TSELDATA,
        productName: Strings.TELKOMSEL_DATA),
    "0813": PrefixPaketDataModel(
        prefix: "0813",
        provider: Constants.SIMPATI,
        productCode: Constants.TSELDATA,
        productName: Strings.TELKOMSEL_DATA),
    "0821": PrefixPaketDataModel(
        prefix: "0821",
        provider: Constants.SIMPATI,
        productCode: Constants.TSELDATA,
        productName: Strings.TELKOMSEL_DATA),
    "0822": PrefixPaketDataModel(
        prefix: "0822",
        provider: Constants.SIMPATI,
        productCode: Constants.TSELDATA,
        productName: Strings.TELKOMSEL_DATA),
    "0823": PrefixPaketDataModel(
        prefix: "0823",
        provider: Constants.AS,
        productCode: Constants.TSELDATA,
        productName: Strings.TELKOMSEL_DATA),
    "0851": PrefixPaketDataModel(
        prefix: "0851",
        provider: Constants.AS,
        productCode: Constants.TSELDATA,
        productName: Strings.TELKOMSEL_DATA),
    "0852": PrefixPaketDataModel(
        prefix: "0852",
        provider: Constants.AS,
        productCode: Constants.TSELDATA,
        productName: Strings.TELKOMSEL_DATA),
    "0853": PrefixPaketDataModel(
        prefix: "0853",
        provider: Constants.AS,
        productCode: Constants.TSELDATA,
        productName: Strings.TELKOMSEL_DATA),
    "0817": PrefixPaketDataModel(
        prefix: "0817",
        provider: Constants.XL,
        productCode: Constants.XLDATA,
        productName: Strings.XL_DATA),
    "0818": PrefixPaketDataModel(
        prefix: "0818",
        provider: Constants.XL,
        productCode: Constants.XLDATA,
        productName: Strings.XL_DATA),
    "0819": PrefixPaketDataModel(
        prefix: "0819",
        provider: Constants.XL,
        productCode: Constants.XLDATA,
        productName: Strings.XL_DATA),
    "0859": PrefixPaketDataModel(
        prefix: "0859",
        provider: Constants.XL,
        productCode: Constants.XLDATA,
        productName: Strings.XL_DATA),
    "0877": PrefixPaketDataModel(
        prefix: "0877",
        provider: Constants.XL,
        productCode: Constants.XLDATA,
        productName: Strings.XL_DATA),
    "0878": PrefixPaketDataModel(
        prefix: "0878",
        provider: Constants.XL,
        productCode: Constants.XLDATA,
        productName: Strings.XL_DATA)
  };
}
